---

- name: disable icinga2 features  # noqa 301
  command: icinga2 feature disable {{ item }}
  with_items:
    "{{ icinga2_master_features_disabled }}"
  notify:
    - restart icinga2
  tags:
    - configure

- include: features/api.yml
- include: features/notification.yml
- include: features/ido.yml
