---

- name: disable icinga2 features
  icinga2_feature:
    name: "{{ item }}"
    state: absent
  loop:
    "{{ icinga2_master_features_disabled }}"
  notify:
    - restart icinga2
  tags:
    - icinga2
    - features

- include: features/api.yml
- include: features/notification.yml
- include: features/ido.yml
