---

- name: check that all necessary information is available
  assert:
    that:
      - icinga2_downtime_comment is defined and icinga2_downtime_comment | length != 0
      - icinga2_downtime_duration is defined and icinga2_downtime_duration | int != 0
      - icinga2_master is defined
      - icinga2_api_user is defined
      - icinga2_api_password is defined
      - icinga2_downtime_system_name is defined

- name: check if the icinga master {{ icinga2_master }} are available
  wait_for:
    host: "{{ icinga2_master }}"
    port: "{{ icinga2_master_port | default(5665) }}"
    delay: 1              # No wait before first check (sec)
    timeout: 5            # Stop checking after timeout (sec)
  ignore_errors: false
  retries: 10
  delay: 10
  tags:
    - icinga2
    - downtime_schedule
    - downtime_remove

# thanks to @nbuchwitz for using his code!
- name: schedule downtime for {{ icinga2_downtime_system_name }} with comment '{{ icinga2_downtime_comment }}'
  uri:
    url: "https://{{ icinga2_master }}:{{ icinga2_master_port | default(5665) }}/v1/actions/schedule-downtime"
    url_username: "{{ icinga2_api_user }}"
    url_password: "{{ icinga2_api_password }}"
    use_proxy: false
    force_basic_auth: true
    validate_certs: false
    method: POST
    http_agent: 'curl/7.69.1'
    timeout: 10
    headers:
      Accept: "application/json"
    body_format: json
    body:
      type: "{{ item.type }}"
      filter: "{{ item.filter }}"
      author: "ansible"
      fixed: true
      comment: "{{ icinga2_downtime_comment }}"
      start_time: "{{ downtime_start }}"
      end_time: "{{ downtime_end }}"
      duration: "{{ icinga2_downtime_duration }}"
  vars:
    downtime_start: "{{ ansible_date_time.epoch }}"
    downtime_end: "{{ downtime_start | int + icinga2_downtime_duration | int * 60 }}"
  loop:
    - { type: "Service", filter: "host.name == \"{{ icinga2_downtime_system_name }}\"" }
    - { type: "Host", filter: "host.name==\"{{ icinga2_downtime_system_name }}\"" }
  become: false
  delegate_to: "{{ icinga2_master }}"
  tags:
    - icinga2
    - downtime_schedule

- name: remove downtime
  uri:
    url: "https://{{ icinga2_master }}:{{ icinga2_master_port | default(5665) }}/v1/actions/remove-downtime"
    url_username: "{{ icinga2_api_user }}"
    url_password: "{{ icinga2_api_password }}"
    use_proxy: false
    force_basic_auth: true
    validate_certs: false
    method: POST
    headers:
      Accept: "application/json"
    body_format: json
    body:
      type: "Downtime"
      filter: "host.name==\"{{ icinga2_downtime_system_name }}\" && downtime.author == \"ansible\""
  become: false
  delegate_to: "{{ icinga2_master }}"
  tags:
    - icinga2
    - downtime_remove
