---

- include_tasks: check_installed.yml

- name: update package cache
  package:
    update_cache: true

- block:
    - name: install icinga2 package via aur
      become: true
      become_user: aur_builder
      aur:
        state: present
        name: icinga2
        repository: "{{ icinga2_repo_archlinux }}"

    - name: install openrc init script
      template:
        src: etc/init/openrc/icinga2.j2
        dest: /etc/init.d/icinga2
        mode: 0755
      when:
        - ansible_service_mgr | lower == "openrc"
  when:
    - icinga2_use_external_repo | bool
    - ansible_os_family | lower == 'archlinux'

- block:
    - name: create policy-rc.d
      copy:
        dest: /usr/sbin/policy-rc.d
        content: |
          #!/bin/sh
          exit 101
        mode: 0755

    - name: install icinga2 packages (redhat based)
      package:
        name: "{{ icinga2_packages }}"
        state: present
      register: icinga2_installer

    - name: do facts module to get latest information
      setup:

    - name: remove policy-rc.d
      file:
        path: /usr/sbin/policy-rc.d
        state: absent
  when:
    - not icinga2_installed
    - ansible_os_family | lower != 'archlinux'

- name: re-read ansible facts
  setup:

- include_tasks: check_installed.yml

- name: detect icinga2_user
  icinga2_prepared_vars:
    variable: ICINGA2_USER
  register: _icinga2_user

- name: detect icinga2_group
  icinga2_prepared_vars:
    variable: ICINGA2_GROUP
  register: _icinga2_group

- name: define icinga2_user to '{{ _icinga2_user.value }}'
  set_fact:
    icinga2_user: "{{ _icinga2_user.value }}"
  when:
    - _icinga2_user.value is defined

- name: define icinga2_group to '{{ _icinga2_group.value }}'
  set_fact:
    icinga2_group: "{{ _icinga2_group.value }}"
  when:
    - _icinga2_group.value is defined

- name: create custom fact file
  template:
    src: facts.d/icinga2.fact.j2
    dest: /etc/ansible/facts.d/icinga2.fact
    owner: root
    group: root
    mode: 0755

- name: do facts module to get latest information
  setup:

...
