---

- name: define primary icinga2 master
  set_fact:
    icinga2_primary_master: "{{ icinga2_masters | reorder_master }}"

- include: prepare.yml
  become: true
  tags:
    - icinga2_all
    - icinga2_prepare

- include: install.yml
  become: true
  tags:
    - icinga2_all
    - icinga2_install

- include_tasks: master.yml
  when: icinga2_mode == 'master'
  tags:
    - icinga2_all
    - icinga2_master

- include_tasks: satellite.yml
  when: icinga2_mode == 'satellite'
  tags:
    - icinga2_all
    - icinga2_satellite

- include_tasks: service.yml
  tags:
    - icinga2_all
    - icinga2_service

# ---------------------------------------------------------------------------------------

- include_tasks: master/backup.yml
  when:
    - icinga2_mode == 'master'
  tags:
    - icinga2_all
    - icinga2_backup

- include_tasks: master/restore.yml
  when:
    - icinga2_mode == 'master'
  tags:
    - icinga2_all
    - icinga2_restore

- include_tasks: downtime.yml
  when:
    - icinga2_mode == 'master'
    - icinga2_downtime_comment is defined and icinga2_downtime_comment | length != 0
    - icinga2_downtime_duration is defined and icinga2_downtime_duration | int != 0
    - icinga2_api.user is defined
    - icinga2_api.password is defined
    - icinga2_downtime_system_name is defined
  tags:
    - icinga2_all
    - icinga2_downtime_schedule
    - icinga2_downtime_remove
