---

- include: preparations.yml
  become: true
  tags:
    - preparations

#- include: variables.yml
#  become: true
#  tags:
#    - preparations

- include_tasks: master.yml
  when: icinga2_mode == 'master'

- include_tasks: satellite.yml
  when: icinga2_mode == 'satellite'

- include_tasks: plugins.yml

- include: custom_checks.yml
  when: icinga2_mode == 'master'

- include: service.yml

- include_tasks: downtime.yml
  tags:
    - icinga2
    - downtime_schedule
    - downtime_remove
  when:
    icinga2_set_downtime | default(False) and
    icinga2_mode == 'master'
