---

- include_tasks: check_installed.yml

- name: install icinga2 packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - icinga2-ido-mysql
    - "{{ icinga2_dependencies }}"

- include_tasks: check_installed.yml

- name: rename some static files
  command: |
    mv /etc/icinga2/conf.d/{{ item }}.conf /etc/icinga2/conf.d/{{ item }}.disabled
  args:
    removes: "/etc/icinga2/conf.d/{{ item }}.conf"
  loop:
    - templates
    - apt

- include_tasks: master/backup.yml
- include_tasks: master/pki.yml
- include_tasks: master/configure.yml
- include_tasks: master/features.yml
- include_tasks: master/global-templates.yml

- name: configure zones
  template:
    src: etc/icinga2/zones.conf.j2
    dest: /etc/icinga2/zones.conf
    mode: 0644
    backup: true

- name: configure local hosts file
  template:
    src: etc/icinga2/hosts.conf.j2
    dest: /etc/icinga2/conf.d/hosts.conf
    mode: 0644
    backup: true

- name: add custom groups to icinga2
  template:
    src: etc/icinga2/conf.d/groups.conf.j2
    dest: /etc/icinga2/conf.d/groups.conf
    mode: 0644
    backup: true
  notify:
    - restart icinga2
  tags:
    - configure

- name: remove static services file
  file:
    name: /etc/icinga2/conf.d/services.conf
    state: absent

- name: create {{ icinga2_local_scriptsdir }} directory
  file:
    path: "{{ icinga2_local_scriptsdir }}"
    state: directory
    mode: 0755
