---

- name: install requirements
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ icinga2_requirements }}"

- name: make sure ansible local facts directory exists
  file:
    dest: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0755

- block:
    - name: add icinga2 repo GPG key
      apt_key:
        # F51A 91A5 EE00 1AA5 D77D  53C4 C6E3 19C3 3441 0682
        id: F51A91A5EE001AA5D77D53C4C6E319C334410682
        url: https://packages.icinga.com/icinga.key

    - name: add icinga2 repo sources
      template:
        src: etc/apt/icinga2.list.j2
        dest: /etc/apt/sources.list.d/icinga2.list
        mode: 0644

    - name: update apt cache
      apt:
        update_cache: true

  when: ansible_os_family | lower == 'debian' and icinga2_use_external_repo | bool

- block:

    - name: Import EPEL GPG key.
      rpm_key:
        key: https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        state: present

    - name: install EPEL repository
      yum_repository:
        name: epel
        state: present
        description: Extra Packages for Enterprise Linux {{ ansible_distribution_major_version }} - $basearch
        baseurl: http://download.fedoraproject.org/pub/epel/{{ ansible_distribution_major_version }}/$basearch
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-{{ ansible_distribution_major_version }}&arch=$basearch&infra=$infra&content=$contentdir
        failovermethod: priority
        gpgcheck: 1
        enabled: 1

    - name: Import Icinga2 GPG key.
      rpm_key:
        key: https://packages.icinga.com/icinga.key
        state: present

    - name: install Icinga2 repository
      yum_repository:
        name: icinga-stable-release
        state: present
        description: ICINGA (stable release for epel)
        baseurl: https://packages.icinga.com/epel/$releasever/release/
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ICINGA
        gpgcheck: 1
        enabled: 1

    - name: update rpm cache  # noqa 303
      command: yum clean metadata
      args:
        warn: false

  when: ansible_os_family | lower == 'redhat' and icinga2_use_external_repo | bool

- block:

    - name: install build tools
      package:
        name: "{{ item }}"
        state: present
      loop:
        - base-devel
        - cmake

    - name: create sudo rules for aur_builder
      copy:
        content: '%aur_builder ALL=(ALL) NOPASSWD: ALL'
        dest: /etc/sudoers.d/aur
        validate: visudo -cf %s

    - name: create build group
      group:
        name: aur_builder

    - name: create build user
      user:
        name: aur_builder
        group: aur_builder

  when: ansible_os_family | lower == 'archlinux' and icinga2_use_external_repo | bool
