---

- include_tasks: check_installed.yml

- block:

    - name: install icinga2 packages
      package:
        name: '{{ item }}'
        state: latest
      loop:
        '{{ icinga2_dependencies }}'
  when: ansible_os_family | lower != 'archlinux'

# - block:
#   - name: add icinga2 repo GPG key
#     apt_key:
#       # F51A 91A5 EE00 1AA5 D77D  53C4 C6E3 19C3 3441 0682
#       id: F51A91A5EE001AA5D77D53C4C6E319C334410682
#       url: https://packages.icinga.com/icinga.key
#
#   - name: add icinga2 repo sources
#     apt_repository:
#       filename: icinga2
#       repo: deb http://packages.icinga.com/ubuntu icinga-{{ ansible_lsb.codename }} main
#   when: (
#     icinga2_use_external_repo | bool and
#     ansible_os_family | lower == 'debian')
#
# - include_tasks: check_installed.yml
#
# - name: Gather Facts
#   setup:

# TODO
# check for updates

- block:
    # - name: install build tools
    #   package:
    #     name: '{{item}}'
    #     state: present
    #   loop:
    #     - base-devel
    #     - cmake
    #
    # - name: create sudo rules for aur_builder
    #   copy:
    #     content: '%aur_builder ALL=(ALL) NOPASSWD: ALL'
    #     dest: /etc/sudoers.d/aur
    #     validate: 'visudo -cf %s'
    #
    # - name: create build group
    #   group:
    #     name: aur_builder
    #
    # - name: create build user
    #   user:
    #     name: aur_builder
    #     group: aur_builder

    - name: download icinga2 package
      become: yes
      become_user: aur_builder
      shell: |
        cd ~
        git clone https://github.com/bodsch/aur-icinga2 icinga2
        cd icinga2/
        git pull

    - name: get package version
      become: yes
      become_user: aur_builder
      shell: |
        cd ~/icinga2/
        grep pkgver= PKGBUILD |awk -F '=' '{printf $2}'
      register: __packaged_icinga2_version

    - name: set package icinga2 version
      set_fact:
        packaged_icinga2_version: "{{ __packaged_icinga2_version.stdout }}"
        cacheable: true
      when: __packaged_icinga2_version is defined and __packaged_icinga2_version.rc is defined and __packaged_icinga2_version.rc == 0

    - block:

      - name: compare versiones
        debug:
          msg: 'current installed version {{icinga2_version}} - we need an update to version {{packaged_icinga2_version}}'
        #when: packaged_icinga2_version is version( icinga2_version ,'>')

      - name: build icinga2 package
        become: yes
        become_user: aur_builder
        shell: |
          cd ~/icinga2/
          makepkg --syncdeps --install --noprogressbar --noconfirm
      when: packaged_icinga2_version is version( icinga2_version ,'>')

  when: (
    icinga2_use_external_repo | bool and
    ansible_os_family | lower == 'archlinux')

- include_tasks: check_installed.yml

- name: rename some static files
  command: |
    mv /etc/icinga2/conf.d/{{ item }}.conf /etc/icinga2/conf.d/{{ item }}.disabled
  args:
    creates: "/etc/icinga2/conf.d/{{ item }}.disabled"
    removes: "/etc/icinga2/conf.d/{{ item }}.conf"
  loop:
    - hosts
    - services
    - templates
    - users
    - apt

- include: satellite/pki.yml
- include: satellite/configure.yml
- include: satellite/features.yml
