---
- hosts: all
  any_errors_fatal: false
  environment:
    NETRC: ''
  vars:

    ansible_python_interpreter: python3

    icinga2_mode: satellite

    icinga2_mainlog_severity: warning

    icinga2_plugins_download:
      - url: 'https://raw.githubusercontent.com/bodsch/check_arch_updates/1.0/check_arch_updates'
        dest: 'check_arch_updates'
        checksum: 'sha256:7afa562aaedb63f6e93cfebfa4a9a3ea49fecda62d4dae3d8ff919b76c117c41'

  roles:
    - role: ansible-icinga2
