---

- name: disable icinga2 features
  icinga2_feature:
    name: "{{ item }}"
    state: absent
  loop:
    - perfdata
    - notification
    - livestatus
    - ido-mysql
  notify:
    - restart icinga2
  tags:
    - icinga2
    - features

# configure API
- block:

    - name: configure api feature
      template:
        src: etc/icinga2/features/api.conf.j2
        dest: /etc/icinga2/features-available/api.conf
        owner: root
        group: root
        mode: 0644

    - name: enable api feature
      icinga2_feature:
        name: api
        state: present
      notify:
        - restart icinga2
      tags:
        - icinga2
        - features
