---

- name: disable icinga2 features  # noqa 301
  command: icinga2 feature disable {{ item }}
  with_items:
    - perfdata
    - notification
    - livestatus
    - ido-mysql
  notify:
    - restart icinga2
  tags:
    - configure

# configure API
- block:

    - name: configure api feature
      template:
        src: etc/icinga2/features/api.conf.j2
        dest: /etc/icinga2/features-available/api.conf
        owner: root
        group: root
        mode: 0644

    - name: enable api feature  # noqa 303
      command: icinga2 feature enable api
      notify:
        - restart icinga2
      tags:
        - configure
