---

- name: get salt from icinga2 master
  command: awk -F'[\"]' '/TicketSalt/ { print $2 }' /etc/icinga2/constants.conf
  register: salt
  delegate_to: "{{ icinga2_server }}"
  changed_when: false

- name: set icinga2_salt
  set_fact:
    icinga2_salt: "{{ salt.stdout }}"
  when: salt.stdout is defined

- name: assert missing salt
  assert:
    that:
      - icinga2_salt | length != 0
    msg: icinga2 salt is missing
    quiet: true

- name: configure icinga2
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - src: etc/icinga2/icinga2.conf.j2
      dest: /etc/icinga2/icinga2.conf
    - src: etc/icinga2/constants.conf.j2
      dest: /etc/icinga2/constants.conf
    - src: etc/icinga2/features/mainlog.conf.j2
      dest: /etc/icinga2/features-available/mainlog.conf
  when: icinga2_salt is defined

- name: configure icinga2 api
  template:
    src: etc/icinga2/features/api.conf.j2
    dest: /etc/icinga2/features-available/api.conf
    mode: 0644

- name: check if the icinga master {{ icinga2_master }} are available
  wait_for:
    host: "{{ icinga2_master }}"
    port: 5665
    delay: 4              # No wait before first check (sec)
    timeout: 5            # Stop checking after timeout (sec)
  ignore_errors: false
  retries: 10
  delay: 10

- name: "create a ticket from icinga2 master for the satellite '{{ icinga2_certificate_cn }}'"
  shell: |
    icinga2 pki ticket --cn {{ icinga2_certificate_cn }} --salt {{ icinga2_salt }}
  register: ticket
  delegate_to: "{{ icinga2_server }}"
  when: icinga2_salt is defined

- name: set facts
  set_fact:
    icinga2_fqdn_ticket: "{{ ticket.stdout }}"

- block:

    - name: set facts
      set_fact:
        icinga2_pki_ca_key: "{{ icinga2_pki_dir }}/ca.key"
        icinga2_pki_ca_cert: "{{ icinga2_pki_dir }}/ca.crt"
        icinga2_pki_fqdn_key: "{{ icinga2_pki_dir }}/{{ ansible_fqdn }}.key"
        icinga2_pki_fqdn_cert: "{{ icinga2_pki_dir }}/{{ ansible_fqdn }}.crt"
        icinga2_pki_master_cert: "{{ icinga2_pki_dir }}/trusted-master.crt"

    - name: create {{ icinga2_pki_dir }}
      file:
        dest: "{{ icinga2_pki_dir }}"
        state: directory
        owner: "{{ icinga2_user }}"

    - name: check if existing key
      stat:
        path: "{{ icinga2_pki_fqdn_key }}"
      register: __satellite_key

    - name: check if existing ca.crt
      stat:
        path: "{{ icinga2_pki_ca_cert }}"
      register: __ca_crt

    - name: copy ca.crt from icinga2 master
      fetch:
        src: "{{ icinga2_pki_ca_cert }}"
        dest: files/ca.crt
        flat: true
      delegate_to: '{{ icinga2_server }}'

    - name: copy ca.crt from icinga2 master
      copy:
        src: files/ca.crt
        dest: "{{ icinga2_pki_ca_cert }}"
        owner: "{{ icinga2_user }}"
        group: "{{ icinga2_user }}"

    - name: configure icinga2 satellite pki
    ## http://lowendbox.com/blog/server-monitoring-with-icinga-2-part-2-the-node-ubuntu-host/
    ## http://serverfault.com/questions/647805/how-to-set-up-icinga2-remote-client-without-using-cli-wizard
      command: "{{ item }}"
      with_items:
        - "icinga2 pki new-cert --cn {{ icinga2_certificate_cn }} --key {{ icinga2_pki_fqdn_key }} --cert {{ icinga2_pki_fqdn_cert }}"
        - "icinga2 pki save-cert --key {{ icinga2_pki_fqdn_key }} --cert {{ icinga2_pki_fqdn_cert }} --trustedcert {{ icinga2_pki_master_cert }} --host {{ icinga2_master }}"
        - "icinga2 pki request --host {{ icinga2_master }} --port {{ icinga2_master_port }} --ticket {{ icinga2_fqdn_ticket }} --key {{ icinga2_pki_fqdn_key }}
          --cert {{ icinga2_pki_fqdn_cert }} --trustedcert {{ icinga2_pki_master_cert }} --ca {{ icinga2_pki_ca_key }}"
        - "icinga2 node setup --ticket {{ icinga2_fqdn_ticket }} --endpoint {{ icinga2_master }} --zone {{ ansible_fqdn }} --parent_host {{ icinga2_master }}
          --trustedcert {{ icinga2_pki_master_cert }}"
      become: true
      when: not __satellite_key.stat.exists and ticket.stdout is defined
      notify:
        - restart icinga2

    - name: fix permissions for icinga2 pki directory  # noqa 301
      command: "{{ item }}"
      args:
        warn: false
      with_items:
        - chown -R {{ icinga2_user }}:{{ icinga2_user }} {{ icinga2_pki_dir }}

    - name: create zone entry on master '{{ icinga2_server }}'
      file:
        dest: /etc/icinga2/zones.d/{{ icinga2_certificate_cn }}
        state: directory
      delegate_to: "{{ icinga2_server }}"

    - name: create zone file on master '{{ icinga2_server }}'
      template:
        src: etc/icinga2/satellite.conf.j2
        dest: /etc/icinga2/satellites.d/{{ icinga2_certificate_cn }}.conf
      delegate_to: "{{ icinga2_server }}"
      notify: restart icinga2 master

    - name: create host object file on master '{{ icinga2_server }}'
      template:
        src: etc/icinga2/satellite-zone.conf.j2
        dest: /etc/icinga2/zones.d/{{ icinga2_certificate_cn }}/{{ icinga2_certificate_cn }}.conf
      delegate_to: "{{ icinga2_server }}"
      notify: restart icinga2 master

  when: icinga2_fqdn_ticket is defined and icinga2_fqdn_ticket | length != 0

- name: ensure that satellite has api connetions
  stat:
    path: "{{ icinga2_certificate_cn }}/_etc/{{ icinga2_certificate_cn }}.conf"
  register: __satellite_api_connections
