---

- name: create notifications directory
  file:
    name: /etc/icinga2/notifications
    state: directory

# configure notification
- block:
    - name: configure notification feature
      template:
        src: etc/icinga2/features/notification.conf.j2
        dest: /etc/icinga2/features-available/notification.conf
        owner: root
        group: root
        mode: 0644

    - name: enable notification feature
      icinga2_feature:
        name: notification
        state: present
      notify:
        - restart icinga2
      tags:
        - icinga2
        - features

  when: icinga2_master_features_enabled | join('|') | regex_search('notification')
