---

- name: create notifications directory
  file:
    name: /etc/icinga2/notifications
    state: directory

- name: define graphite feature state
  set_fact:
    feature_notification_state: "{{ 'present' if icinga2_master_features_enabled | join('|') | regex_search('notification') else 'absent' }}"

- name: configure notification feature
  template:
    src: etc/icinga2/features/notification.conf.j2
    dest: /etc/icinga2/features-available/notification.conf
    owner: root
    group: root
    mode: 0644

- name: enable notification feature
  icinga2_feature:
    name: notification
    state: "{{ feature_notification_state }}"
  notify:
    - restart icinga2
  tags:
    - icinga2
    - features
