---
- hosts: all
  any_errors_fatal: false
  environment:
    NETRC: ''
  vars:

    ansible_python_interpreter: python3

    mariadb_use_external_repo: false

    mariadb_bind_address: 127.0.0.1
    mariadb_root_password: root
    mariadb_max_connections: 20

    mariadb_databases:

      - name: icinga2_ido
#        collation: utf8mb4_bin
#        encoding: utf8mb4

    mariadb_users:

      - name: icinga2_ido
        host: 127.0.0.1
        password: icinga2
        priv: "icinga2_ido.*:ALL"

    icinga2_mode: master

    icinga2_masters:
      debian-10:

    icinga2_sudo_cmd:
      - /sbin/service foo restart

    icinga2_api:
      user:
        root:
          password: foo
          permissions: '*'

    icinga2_ido:
      username: icinga2_ido
      password: icinga2
      # socket: /var/lib/mysql/mysql.sock
      cleanup:
        acknowledgements_age: 48h
        hostchecks_age: 48h
        servicechecks_age: 48h

    # icinga2_mainlog_severity: warning

    icinga2_master_features_enabled:
      - checker
      - api
      - ido-mysql
      - mainlog
      # - graphite

    #icinga2_features:
    #  graphite:
    #    graphite_host: localhost

    #icinga2_plugins_download:
    #  - url: 'https://raw.githubusercontent.com/bodsch/check_arch_updates/1.0/check_arch_updates'
    #    dest: 'check_arch_updates'
    #    checksum: 'sha256:7afa562aaedb63f6e93cfebfa4a9a3ea49fecda62d4dae3d8ff919b76c117c41'

    icinga2_host_object:
      localhost:
        import: generic-host
        address: '{{ ansible_default_ipv4.address }}'
        display_name: "{{ ansible_fqdn }}"
        vars: |
          os = "Linux"
          dist = "{{ ansible_distribution }}"
          dist_ver = "{{ ansible_distribution_version }}"
          disks = {
            "disk /" = {
              disk_partitions = "/"
            }
          }

    icinga2_salt: tmpams80tqx

  # pre_tasks:
  #   - name: clean caches for debian based
  #     command: apt clean
  #     args:
  #       warn: false
  #     when: ansible_os_family | lower == 'debian'

  roles:
    - role: mariadb
    - role: ansible-icinga2

  # tasks:
  #   # - include: ../../tasks/master/features.yml
  #   #   tags:
  #   #     - features
  #   - include: ../../tasks/downtime.yml
  #     vars:
  #       icinga2_master: '{{ ansible_default_ipv4.address }}'
  #       icinga2_api.user: root
  #       icinga2_api.password: foo
  #       icinga2_downtime_comment: Downtime for deployment
  #       icinga2_downtime_system_name: localhost
  #       icinga2_downtime_duration: 120
  #
  #     tags:
  #       - downtime_schedule

